#!/usr/bin/env python 
# Print duplicates files found in HASHDEEP file

import argparse
import csv
import itertools

HEADER = 5    # First five lines are comments
SIZE = 0      # First column is file size
MD5 = 1       # Secood column is MD5 hash
SHA256 = 2    # Third column is SHA256 hash
FILENAME = 3  # Forth column is file name

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("file1", type=argparse.FileType('r'))
    return parser.parse_args()

def duplicates(file1):
    shasum = {}
    for row in itertools.islice(file1, HEADER, None):
        sha = row[SHA256]
        if sha in shasum:
            print(row[FILENAME])
        else:
            shasum[row[SHA256]] = row[FILENAME]

def main():
    args = parse_args()
    file1 = csv.reader(args.file1)

    duplicates(file1)


if __name__ == "__main__":
    main()
