#!/bin/bash
# Add missing tags to JCPenney Portrait Studio pictures

usage() {
    echo "Usage: jcp_add_tags [DIRS]"
    exit 1
}

LATITUDE=38.59584
LONGITUDE=89.97979  # Minus

if [[ $# -eq 0 ]]
then
    usage
fi

# Preserve time stamp (on POSIX) and create date (on macOS)
# Do not overwrite existing tags
exec exiftool -P -overwrite_original_in_place \
              '-artist-='           '-artist=JCPenney Portrait Studio' \
              '-CreateDate-='       '-CreateDate<FileCreateDate' \
              '-DateTimeOriginal-=' '-DateTimeOriginal<FileCreateDate' \
              '-GPSTimeStamp-='     '-GPSTimeStamp<FileCreateDate' \
              '-GPSDateStamp-='     '-GPSDateStamp<FileCreateDate' \
              '-GPSLatitude-='      "-GPSLatitude=$LATITUDE" \
              '-GPSLatitudeRef-='   "-GPSLatitudeRef=$LATITUDE" \
              '-GPSLongitude-='     "-GPSLongitude=$LONGITUDE" \
              '-GPSLongitudeRef-='  "-GPSLongitudeRef=-$LONGITUDE" \
              '-model-='            '-model=studio' \
              '-Xmp-dc:Type-=studio'   '-Xmp-dc:Type+=studio' \
              '-Xmp-dc:Type-=portrait' '-Xmp-dc:Type+=portrait' \
			  '-Xmp:LocationShownCity=Fairview Heights' \
			  '-Xmp:LocationShownProvinceState=Illinois' \
		      '-Xmp:LocationShownSublocation=St. Clair Square Mall' \
              -r -- "$@"
