#!/usr/bin/env python 
#
# $ local2utc "2017:05:21 09:35:59-05:00"
# 2017:05:21 14:35:59

import pytz
import sys

from  datetime import datetime

def isoformat(time):
	Y, M, D, h, m, s, oh, om, _ = \
		time.strip().replace(' ', ':').replace('-', ':').split(':')

	return f"{Y}-{M}-{D} {h}:{m}:{s}-{oh}:{om}"

local_time = datetime.fromisoformat(isoformat(sys.argv[1]))
utc_time = local_time.astimezone(pytz.utc)
print(utc_time.strftime("%Y:%m:%d %H:%M:%S"))
